[09:30:10 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[09:30:31 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[09:30:55 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:16:09 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:16:13 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:17:39 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:18:02 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:19:55 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:20:14 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:20:59 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:11 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:34 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:21:34 22-01-2018] (Error) dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:22:39 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:23:48 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:24:35 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:24:49 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:25:00 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:16 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:38 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:26:46 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:17 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:34 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:27:49 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.14: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[14:43:14 22-01-2018] (Error) E:\Entwicklung\Projects\Python\dash\config_handler.py::setup_store.15: Error: Database was already created. You can reset it with the '-r' option.
table configs already exists
[23:33:06 22-01-2018] (Success) server.py::logout.114: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[23:33:32 22-01-2018] (Success) server.py::logout.114: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[23:38:31 22-01-2018] (Success) server.py::logout.120: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[08:51:52 23-01-2018] (Success) server.py::logout.120: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:30:15 23-01-2018] (Success) server.py::logout.123: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:31:21 23-01-2018] (Success) server.py::logout.123: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:31:57 23-01-2018] (Success) server.py::logout.123: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:32:14 23-01-2018] (Success) server.py::logout.123: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:33:41 23-01-2018] (Success) server.py::logout.124: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:34:14 23-01-2018] (Success) server.py::logout.124: Benutzer warwickx@web.de wurde erfolgreich ausgeloggt.
[09:45:58 23-01-2018] (Success) server.py::logout.124: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:46:06 23-01-2018] (Success) server.py::logout.124: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:46:17 23-01-2018] (Success) server.py::logout.124: Benutzer warwickx@web.de wurde erfolgreich ausgeloggt.
[09:49:46 23-01-2018] (Success) server.py::logout.127: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:53:52 23-01-2018] (Success) server.py::logout.136: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[09:56:40 23-01-2018] (Success) server.py::logout.143: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[10:01:28 23-01-2018] (Success) server.py::logout.143: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[10:16:54 23-01-2018] (Success) server.py::logout.148: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[10:17:03 23-01-2018] (Success) server.py::logout.148: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[10:17:11 23-01-2018] (Success) server.py::logout.148: Benutzer warwickx@web.de wurde erfolgreich ausgeloggt.
[22:52:07 23-01-2018] (Success) server.py::logout.148: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[22:52:19 23-01-2018] (Success) server.py::logout.148: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[08:23:01 24-01-2018] (Success) server.py::logout.173: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[08:56:24 24-01-2018] (Success) server.py::logout.189: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[21:05:13 26-01-2018] (Error) server.py::handle_register.136: Error at registering new user marc-friedrich94@web.de with exception:
'Cursor' object has no attribute 'commit'
[21:09:03 26-01-2018] (Success) server.py::handle_register.146: New registration: marc-friedrich94@web.de
[21:10:56 26-01-2018] (Success) server.py::logout.195: Benutzer marc-friedrich94@web.de wurde erfolgreich ausgeloggt.
[21:11:10 26-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[13:52:13 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[13:52:24 30-01-2018] (Success) server.py::logout.195: Benutzer marc-friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:13:17 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:13:39 30-01-2018] (Success) server.py::logout.195: Benutzer warwickx@web.de wurde erfolgreich ausgeloggt.
[14:22:35 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:22:47 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:33:53 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:34:01 30-01-2018] (Success) server.py::handle_register.146: New registration: a@a.de
[14:34:18 30-01-2018] (Success) server.py::logout.195: Benutzer a@a.de wurde erfolgreich ausgeloggt.
[14:48:30 30-01-2018] (Success) server.py::logout.195: Benutzer marc.friedrich94@web.de wurde erfolgreich ausgeloggt.
[14:48:51 30-01-2018] (Error) server.py::admin_cp.207: User warwickx@web.de tried to access the Administrator Control Panel.
[14:49:03 30-01-2018] (Success) server.py::logout.195: Benutzer warwickx@web.de wurde erfolgreich ausgeloggt.
[14:49:04 30-01-2018] (Error) server.py::admin_cp.211: Unauthenticated user tried to access the Administrator Control Panel.
[14:50:07 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[14:50:26 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[14:50:57 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[14:51:32 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[14:56:01 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[14:57:52 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:00:02 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:00:26 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:01:00 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:01:01 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:02:32 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:02:42 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:03:22 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:03:52 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:04:12 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:04:38 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:04:48 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:04:55 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
[15:04:56 30-01-2018] (Success) server.py::admin_cp.215: Administrator marc.friedrich94@web.de accessed the Administrator Control Panel.
